# Generated by Django 3.2.7 on 2021-09-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='info',
        ),
    ]
