# Generated by Django 3.2.7 on 2021-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_thing_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='info',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
